<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('We Met At Zendcon'); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink()
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.23/browser.min.js')
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/react/0.14.0/react.js')
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/react/0.14.0/react-dom.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="jumbotron">We Met At Zendcon</div>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript()->prependFile($this->basePath().'/js/wmaz.js', 'text/babel'); ?>
    </body>
</html>
