<div class="row text-center">
    Add your twitter handle to the path to see how you connect with everyone who is here.
</div>
<div class="row">
    <div class="center-block" id="twitter-block">
        <i class="fa fa-twitter"></i><input type="text" id="twitterHandle" placeholder="@YourTwitterHandle" title="Add your Twitter handle here to add yourself to this path."/>
    </div>
</div>
<div id="pathHistory" class="row"></div>